### PR TITLE
Lesson_1_Setup_React_App.md

### PR DESCRIPTION
**Pull request by anymose96**
translated by anymose Dec 23 2021

### CODE REVIEW

**Comment by anymose96** [comment]
Lesson_1_Setup_React_App.md

**Comment by anymose96** [comment]
Lesson_2_Deploy_To_Real_Testnet.md

**Comment by anymose96** [comment]
Lesson_3_Connect_Wallet_To_Web_App.md

**Comment by anymose96** [comment]
Lesson_4_Call_Deployed_Contract.md

**Review by bobjiang — APPROVED** [review]

**Pull request merged**
